.IWLListviewWidgetViewLeaderboard .IWLListviewItem {
	height: 3.929em;
}

.IWLListviewWidgetViewLeaderboard .IWLListviewItemAttributeLabel,
	.IWLListviewWidgetViewLeaderboard .IWLListviewItemAuthorNameLinkContainer, 
	 	.IWLListviewWidgetViewLeaderboard .IWLListviewItemLastActivityDateContainer, 
	 		.IWLListviewWidgetViewLeaderboard .IWLListviewItemStatusContainer {
	display:none;
} 

.IWLListviewWidgetViewLeaderboard .IWLListviewItemRatingLabel,
	.IWLListviewWidgetViewLeaderboard .IWLListviewItemLikesLabel,
		.IWLListviewWidgetViewLeaderboard .IWLListviewItemFeedSizeLabel {
	display:block;
	font-size: 0.786em !important;
	position:absolute; 
	margin-top: 1.573em;	
}

.IWLListviewWidgetViewLeaderboard .IWLListviewItemTitle {
	  min-height: inherit;
}